#Determinan

Determinan adalah nilai skalar yang diperoleh dari suatu matriks persegi. Untuk matriks persegi \( $ n \times n $), determinan memberikan informasi tentang bagaimana matriks tersebut mempengaruhi perubahan volume dalam transformasi linier. Jika determinan suatu matriks tidak nol, maka matriks tersebut bersifat invertible (memiliki invers), sedangkan jika determinannya nol, matriks tersebut tidak memiliki invers.

Contoh:
Misalkan kita memiliki matriks 2x2:
\[ A = \begin{bmatrix} 2 & 3 \\ 1 & 4 \end{bmatrix} \]

Untuk menghitung determinan matriks \( A \), kita gunakan rumus:

$[ \text{det}(A) = ad - bc ]$

$[ \text{det}(A) = (2 \times 4) - (3 \times 1) ]$

$[ \text{det}(A) = 8 - 3 ]$

$[ \text{det}(A) = 5 ]$

Jadi, determinan dari matriks \( A \) adalah 5.

Contoh lainnya, untuk matriks 3x3:
\[ B = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 1 & 4 \\ 5 & 6 & 0 \end{bmatrix} \]

Rumus determinan untuk matriks 3x3 adalah lebih kompleks, namun untuk contoh ini, kita dapat menggunakan metode ekspansi kofaktor atau aturan Sarrus. Setelah menghitung, kita dapat menemukan determinan dari matriks \( B \).

Tentu, berikut adalah beberapa sifat-sifat dari determinan beserta contohnya:

1. **Determinan dari Identitas**: Determinan dari matriks identitas \(I_n\) dengan ordo \(n \times n\) adalah 1.
   
   Contoh:
   $[I_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}]$
   Determinan dari \(I_3\) adalah 1.

2. **Perubahan Urutan Baris**: Jika dua baris dari suatu matriks ditukar, maka determinannya akan mengalami perubahan tanda.

   Contoh:
   Misalkan \(A\) adalah matriks 2x2:
   $[
   A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
   ]$
   $[
   \text{det}(A) = ad - bc
   ]$
   Jika kita tukar baris pertama dan kedua, maka matriksnya menjadi:
   $[
   A' = \begin{bmatrix} c & d \\ a & b \end{bmatrix}
   $]
   $[
   \text{det}(A') = cd - da = -(ad - bc) = -\text{det}(A)
   ]$

3. **Penggandaan Sebuah Baris**: Jika suatu matriks memiliki dua baris yang identik, maka determinannya adalah nol.

   Contoh:
   Misalkan \(B\) adalah matriks 3x3:
   $[
   B = \begin{bmatrix} 1 & 2 & 3 \\ 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
   $]
   Determinan dari \(B\) adalah 0 karena baris pertama dan kedua identik.

4. **Penjumlahan Skalar ke Sebuah Baris**: Jika suatu matriks memiliki baris yang merupakan jumlah dari dua baris lainnya, maka determinannya tidak berubah jika baris tersebut digantikan dengan baris asalnya ditambah dengan baris hasil penjumlahan tersebut.

   Contoh:
   Misalkan \(C\) adalah matriks 3x3:
   $[
   C = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}
   $]
   
   Jika kita menggantikan baris ketiga dengan baris ketiga yang baru \( \begin{bmatrix} 7 & 8 & 9 \end{bmatrix} + \begin{bmatrix} 1 & 2 & 3 \end{bmatrix} = \begin{bmatrix} 8 & 10 & 12 \end{bmatrix} \), determinan dari matriks tersebut tidak berubah.

Sifat-sifat tersebut sering digunakan dalam perhitungan determinan dan membantu dalam memahami sifat-sifat dasar dari matriks.

In [1]:
import numpy as np

# Matriks A
A = np.array([[2, 3],
              [1, 4]])

# Matriks B
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Fungsi untuk menampilkan matriks beserta determinannya
def print_matrix_and_determinant(matrix):
    print("Matriks:")
    print(matrix)
    determinant = np.linalg.det(matrix)
    print("Determinan:", determinant)
    print()

# Menampilkan matriks A beserta determinannya
print("Matriks A:")
print_matrix_and_determinant(A)

# Menampilkan matriks B beserta determinannya
print("Matriks B:")
print_matrix_and_determinant(B)


Matriks A:
Matriks:
[[2 3]
 [1 4]]
Determinan: 5.000000000000001

Matriks B:
Matriks:
[[1 2 3]
 [0 1 4]
 [5 6 0]]
Determinan: 0.9999999999999964



#Matrix segitiga atas

In [2]:
import numpy as np

# Membuat matriks segitiga atas
A_upper = np.array([[1, 2, 3],
                    [0, 4, 5],
                    [0, 0, 6]])

print("Matriks segitiga atas:")
print(A_upper)


Matriks segitiga atas:
[[1 2 3]
 [0 4 5]
 [0 0 6]]


#Matrix segitiga bawah

In [3]:
import numpy as np

# Membuat matriks segitiga atas
A_upper = np.array([[1, 2, 3],
                    [0, 4, 5],
                    [0, 0, 6]])

print("Matriks segitiga atas:")
print(A_upper)


Matriks segitiga atas:
[[1 2 3]
 [0 4 5]
 [0 0 6]]


#Determinan dengan menggunakan metode ekspansi kofaktor


Ekspansi kofaktor adalah metode yang digunakan untuk menghitung determinan suatu matriks persegi dengan cara menguraikan determinan tersebut menjadi jumlah produk antara elemen-elemen matriks dengan kofaktor mereka.


Tentu, berikut adalah langkah-langkah untuk menghitung determinan menggunakan metode kofaktor:

1. **Matriks A (2x2)**:
   $[
   A = \begin{bmatrix} 2 & 3 \\ 1 & 4 \end{bmatrix}
   ]$
   Misalkan \(A\) adalah matriks 2x2 tersebut. Untuk menghitung determinan menggunakan metode kofaktor, kita gunakan rumus:
   $[
   \text{det}(A) = a_{11}C_{11} + a_{12}C_{12}
   ]$
   dengan $(C_{ij})$ adalah kofaktor dari elemen $(a_{ij})$. Kofaktor dari elemen $(a_{ij})$ dapat dihitung dengan mengalikan koefisien (-1)^{i+j} dengan determinan minor yang dihasilkan dari menghapus baris ke-i dan kolom ke-j.

2. **Matriks B (3x3)**:
   $[
   B = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 1 & 4 \\ 5 & 6 & 0 \end{bmatrix}
   ]$
   Misalkan $(B)$ adalah matriks 3x3 tersebut. Untuk menghitung determinan menggunakan metode kofaktor, kita gunakan rumus:
   $[
   \text{det}(B) = a_{11}C_{11} + a_{12}C_{12} + a_{13}C_{13}
   ]$
   dengan $(C_{ij})$ adalah kofaktor dari elemen $(a_{ij})$. Kofaktor dari elemen $(a_{ij})$ dapat dihitung dengan mengalikan koefisien (-1)^{i+j} dengan determinan minor yang dihasilkan dari menghapus baris ke-i dan kolom ke-j.

Setelah menghitung kofaktor dan determinan minor, kita dapat menentukan determinan matriks tersebut dengan menjumlahkan hasil perkalian elemen matriks dengan kofaktor yang sesuai.